[project]
name = "image-recognition-give-book"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.109.1",
    "pydantic>=2.11.9",
    "tabulate>=0.9.0",
]
